### PR TITLE
updated for debian

### PR DESCRIPTION
**Pull request by sillycoda**
Greetings,

Thank you for your incredible work on getting these scripts developed. I'm really grateful :) I noticed the shell script needed an additional tag for chromium and not chromium-browser.. please take a look and let me know.. Tested and verified on Debian 11 Bullseye. Thanks!

### CODE REVIEW

**Comment by Yokozuna59** [comment]
Hi there @sillycoda!

I'm the one who should thank you, I didn't think that anyone would use my script. I'm really grateful for you contribution! I have tested it on my Ubuntu 22.04 and it's work very well.

I'm gonna merge to master. And thank you again!

**Comment by sillycoda** [comment]
Thank you! I'm already using your script in my application and I am incredibly grateful! Would you be willing to expand upon that script to install Chromium itself? That would make it an incredibly powerful AIO script!

Thank you again!
~sc

**Comment by Yokozuna59** [comment]
Thank you again!

> Would you be willing to expand upon that script to install Chromium itself?

The main purpose of this script is to install WebDriver to available browsers the user has. I don't think it's a good idea to ask more questions to verify that the users want's that browser and then downloads it's WebDriver or force them to download another browser they aren't welling to use.
For example, if the user want to update his local WebDrivers after he updated his browsers, should he asked those questions again and again every time just for updating his WebDrivers?

I think there are more important features and bug fixes to consider rather than forcing the users over a browser. For example, supporting edge browser WebDriver and so on.

**Comment by sillycoda** [comment]
Yep! I just modified it only slightly to work for my project's needs, and figured you could keep the ball rolling on remaining browsers if need be.. I see your point though; not worth merging this fork, it would be better off without installing browser if the end user doesn't need it..

**Pull request merged**
